### ISSUE TITLE
Error: Could not find a schema

### ISSUE THREAD

**Issue by DavidNelsonCordelia** [awsdocs/aws-codebuild-user-guide#32]
am using the amplify console which i believe uses codebuild.   I get the following error which I have no clue on where to go to deal with.

                                # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-06-13T03:19:08.118Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-06-13T03:19:08.124Z [INFO]: # Start initializing Amplify environment: prod
                                 # Initializing new Amplify environment: prod (amplify init)
2019-06-13T03:19:12.022Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-06-13T03:19:12.800Z [INFO]: 
2019-06-13T03:19:12.800Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2019-06-13T03:19:12.868Z [WARNING]: - Initializing your environment: prod
2019-06-13T03:19:13.294Z [WARNING]: ✔ Initialized provider successfully.
019-06-13T03:19:05.065Z [INFO]: Git SSH Key acquired
2019-06-13T03:19:05.170Z [INFO]: Cloning repository: git@github.com:katenelson42/onlinecoop.git
2019-06-13T03:19:05.294Z [INFO]: Agent pid 67
2019-06-13T03:19:05.299Z [WARNING]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2019-06-13T03:19:05.322Z [WARNING]: Cloning into 'onlinecoop'...
2019-06-13T03:19:05.383Z [WARNING]: Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
2019-06-13T03:19:06.190Z [INFO]: Switching to commit: f83bbe61d7cf1843ca5d107457d8d50ec39611ba
2019-06-13T03:19:06.227Z [WARNING]: Note: checking out 'f83bbe61d7cf1843ca5d107457d8d50ec39611ba'.
                                    You are in 'detached HEAD' state. You can look around, make experimental
                                    changes and commit them, and you can discard any commits you make in this
                                    state without impacting any branches by performing another checkout.
                                    If you want to create a new branch to retain commits you create, you may
                                    do so (now or later) by using -b with the checkout command again. Example:
                                    git checkout -b <new-branch-name>
                                    HEAD is now at f83bbe6... Switched graphql back to cognito
2019-06-13T03:19:06.227Z [INFO]: Checking for Git submodules at: /codebuild/output/src082925135/src/onlinecoop/.gitmodules
2019-06-13T03:19:06.258Z [INFO]: Retrieving cache...
2019-06-13T03:19:06.302Z [INFO]: Extracting cache...
2019-06-13T03:19:06.415Z [INFO]: Extraction done...
2019-06-13T03:19:06.416Z [INFO]: Retrieving environment cache...
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-06-13T03:19:08.118Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-06-13T03:19:08.124Z [INFO]: # Start initializing Amplify environment: prod
                                 # Initializing new Amplify environment: prod (amplify init)
2019-06-13T03:19:12.022Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-06-13T03:19:12.800Z [INFO]: 
2019-06-13T03:19:12.800Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2019-06-13T03:19:12.868Z [WARNING]: - Initializing your environment: prod
2019-06-13T03:19:13.294Z [WARNING]: ✔ Initialized provider successfully.
2019-06-13T03:19:13.449Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2019-06-13T03:19:13.449Z [WARNING]: ✖ There was an error initializing your environment.
2019-06-13T03:19:13.449Z [INFO]: init failed
2019-06-13T03:19:13.474Z [INFO]: Error: Could not find a schema at /codebuild/output/src082925135/src/onlinecoop/amplify/backend/api/mfcPosApi/schema.graphql
                                 at /home/circleci/repo/packages/graphql-transformer-core/src/util/amplifyUtils.ts:207:15
                                 at step (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:40:23)
                                 at Object.next (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:21:53)
                                 at fulfilled (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:12:58)
                                 at <anonymous>
2019-06-13T03:19:13.482Z [ERROR]: !!! Build failed
2019-06-13T03:19:13.482Z [ERROR]: !!! Non-Zero Exit Code detected
2019-06-13T03:19:13.482Z [INFO]: # Starting environment caching...
2019-06-13T03:19:13.483Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by markiver** [comment]
Hello David,

I apologize for the frustration this issue is causing. This is a repository for CodeBuild documentation and is not regularly monitored by the best resources to help you. Please consider one of the following:

- CodeBuild developer forum - https://forums.aws.amazon.com/forum.jspa?forumID=230
- CodeBuild on StackOverflow - https://stackoverflow.com/search?q=codebuild
- CodeBuild on Twitter - https://twitter.com/search?q=codebuild

You might also consider signing up for AWS technical support: https://aws.amazon.com/premiumsupport/. 

Note that a quick search for "Could not find a schema at" and "aws" and "amplify" turns up this page: https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformer-core/src/util/amplifyUtils.ts. That file contains the error message you are receiving, so you might also want to investigate there.

Kind regards,

Mark

**Comment by DavidNelsonCordelia** [comment]
Thanks for the suggestios @markiver
